//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgetCard
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string TemporaryCard { get; set; }
        public System.Guid GateId { get; set; }
        public string SecurityName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string ReasonDelete { get; set; }
        public string SecurityDelete { get; set; }
        public Nullable<System.Guid> Reason { get; set; }
        public string ReasonOthers { get; set; }
    }
}
