//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrDeptMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrDeptMaster()
        {
            this.ApplicationConfig = new HashSet<ApplicationConfig>();
            this.HrDeptMaster1 = new HashSet<HrDeptMaster>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string EnName { get; set; }
        public string KoName { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Parent { get; set; }
        public string ParentCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationConfig> ApplicationConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrDeptMaster> HrDeptMaster1 { get; set; }
        public virtual HrDeptMaster HrDeptMaster2 { get; set; }
    }
}
