//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassingGoodsMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassingGoodsMaster()
        {
            this.PassingGoodsDetail = new HashSet<PassingGoodsDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Applicant { get; set; }
        public int DeptId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public Nullable<bool> ReImport { get; set; }
        public Nullable<System.DateTime> ReImportDate { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<bool> FinishApplication { get; set; }
        public string FinishReason { get; set; }
        public Nullable<System.Guid> ApprovalKind { get; set; }
        public string ApprovalLine { get; set; }
        public string ApprovalLineJson { get; set; }
        public Nullable<System.Guid> ApprovalStatus { get; set; }
        public string NextApprover { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> Temp { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExportUid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassingGoodsDetail> PassingGoodsDetail { get; set; }
    }
}
