//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassingGoodsDetail
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string ItemName { get; set; }
        public string Serial { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public string ItemLocation { get; set; }
        public Nullable<bool> ReImport { get; set; }
        public Nullable<System.DateTime> ReImportDate { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string ImportUid { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public string Remark { get; set; }
    
        public virtual PassingGoodsMaster PassingGoodsMaster { get; set; }
    }
}
