//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysCategory()
        {
            this.SysCategoryValue = new HashSet<SysCategoryValue>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string CreateUid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    
        public virtual HrEmpMaster HrEmpMaster { get; set; }
        public virtual HrEmpMaster HrEmpMaster1 { get; set; }
        public virtual HrEmpMaster HrEmpMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysCategoryValue> SysCategoryValue { get; set; }
    }
}
