//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCheckingDaily
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string ScanTime { get; set; }
        public Nullable<bool> IsCheckIn { get; set; }
        public Nullable<System.Guid> GateId { get; set; }
        public string Remark { get; set; }
        public string VehicleCard { get; set; }
        public string CreateUid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ChangeDriver { get; set; }
    
        public virtual VisitorApplicationDetailVehicle VisitorApplicationDetailVehicle { get; set; }
    }
}
