//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security___Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorApplicationDetailVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitorApplicationDetailVehicle()
        {
            this.VehicleCheckingDaily = new HashSet<VehicleCheckingDaily>();
        }
    
        public int Id { get; set; }
        public int ApplicationMaster { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string DriverPlate { get; set; }
        public string DriverName { get; set; }
        public string PhoneDriver { get; set; }
        public System.Guid VehicleType { get; set; }
        public string VehicleCard { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedUid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    
        public virtual VisitorApplicationMaster VisitorApplicationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleCheckingDaily> VehicleCheckingDaily { get; set; }
    }
}
